// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psawoufrybwtgapputur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzYXdvdWZyeWJ3dGdhcHB1dHVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MzI4MjgsImV4cCI6MjA2MjAwODgyOH0.X1bdWLDd5sPxQo-MGDIM-L40k24OgMdaKB5yzNfeGDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);